import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import { useContext, useState } from "react";
import styled from "styled-components";
import data from "../../articles.json";
import ArticleCard from "../components/ArticleCard";
import GenericList from "../components/GenericList";
import { ArticleContext } from "../contexts/ArticleContext";
const Home: NextPage = () => {
  const { articles } = useContext(ArticleContext);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <S.Main>
        <Link href={"/article/create"}>Create article</Link>
        <GenericList
          data={articles}
          keyExtractor={({ id }) => id}
          render={(item) => {
            return <ArticleCard {...item} />;
          }}
        />
      </S.Main>
    </div>
  );
};

export default Home;

const S = {
  Main: styled.main``,
};
